name: Deploy to solairaj.rf.gd

on:
  push:
    branches: [ master ]

jobs:
  deploywithftp:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying with FTP
        uses: actions/checkout@v2
      - run: echo ${{secrets.EPZY_PASS}}
      - run: make pass="password"